baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 're-cover theme demo'
theme = 'recover'

# Sample params from an AA group format

[params]
    meeting = "Your Meeting Name"
    description = "A Hugo Theme enabling recovery groups to easily maintain a clean, readable, easily accessible web site for group members."
    metaimage = "/images/ogbeagle.png"
    type = "Your Meeting Type Here"
    location = "XYZ Church Room 987"
    address = "123 Main Street, City, ST 77995"
    googlemap = "https://www.google.com/maps"
    groupImage = "/images/group.svg"
    # google analytics tag
    gtag = ""
    time = "12p Mondays - Fridays"
    altTime = "10am Saturdays"
    zoom = "https://zoom.us/"
    zoomtime = "12p Wednesday"
    altzoom = "https://zoom.us/"
    altzoomtime = "10a Saturday"
    greeting = "Welcome to the ABC Group of Alcoholics Anonymous. My name is _______, and I  am an alcoholic. My sobriety date is________. Let's begin today's meeting with a moment  of silence followed by the Serenity Prayer."
    preamble = "Alcoholics Anonymous is a fellowship of men & women who share their  experience, strength, and hope with each other that they may solve their common problem  and help others to recover from alcoholism. The only requirement for membership is a  desire to stop drinking. There are no dues or fees for AA membership. We are self supporting through our own contributions. AA is not allied with any sect, denomination,  politics, organization or institution; does not wish to engage itself in any controversy;  neither endorses nor opposes any causes. Our primary purpose is to stay sober and to help  other alcoholics achieve sobriety."
    preamblepic = "/images/preamble.svg"
    guidlines = "This is a closed meeting of Alcoholics Anonymous; attendance at closed meetings is limited to persons who have a desire to stop drinking. If you think you have a problem with alcohol, you are welcome to attend this meeting. In order to meet our primary purpose we ask that all persons identify themselves only by name and as an alcoholic during this meeting regardless of membership in  programs that deal with “issues other than alcoholism”. We request that all participants refrain from discussion of drugs and other addictions during this meeting. The Group does not condone profanity, please leave street language on the street! We ask that those of you with cell phones and pagers please mute them at this time. Also remember that “Anonymity is the spiritual foundation of all of our traditions, ever reminding us that “who you see here, what you hear here, when you leave here let it stay here!”"
    guidelinesimage = "/images/terms.svg"
    about = "All about your group here. Edit the config.toml file to include any public information about the group."
    chairguidelines = "Thank you for your willingness to be of service to the group and AA by acting as chairperson for your designated meeting. By accepting this responsibility you  agree to either be personally present at the meeting or to be responsible for recruiting  another AA member with one year or more of continuous sobriety. This person should be  knowledgeable in the application of the 12 steps. They agree to be present at the meeting and will serve as chairman for the meeting. The following are suggestions for leading the meeting which have been discussed by The Group Conscience:"
    announcements = "current announcements go here. Edit the config.toml file to add your announcements"
    announcementspic = "/images/news.svg"
    opening = "Is anyone here for their first AA meeting? Is anyone visiting this group for the first time that would like to be recognized?"
    directions = "This is a large group, therefore we ask that you be brief in your sharing so that others may also have the opportunity to participate in the meeting. Does anyone have a problem staying sober today? Does anyone have a topic pertaining to alcoholism that they would like to hear discussed? If not, the topic that I have prepared for today is:"
    meetingpic = "/images/new.svg"
    tradition7 = "Halfway through the meeting - 7th Tradition - “the seventh tradition states we are self-supporting through our own contributions.” A Venmo donation link to @Beagle-Pack is also available online:"
    ending = "At the end of the meeting, give out sobriety chips, and then close with the Lord's Prayer. Return books, basket, cart, etc. to Beagle Pack's room. Give collection to one of the designated people. Ensure attendance and collection are recorded in the group book."
    venmo = "https://venmo.com/"

[menu]
 [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
 [[menu.main]]
    name = "Donations"
    url = "https://venmo.com/"
    weight = 2
    
[module]
  [module.hugoVersion]
    extended = true
    min = ""
    max = ""
